### ISSUE TITLE
[Enhancement] Gen KCL schema from protobuf message

### ISSUE THREAD

**Issue by Peefy** [kcl-lang/kcl-go#302]
## Enhancement

We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.

## Reference

+ Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
+ Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go

## Features

+ [x] Message
+ [x] Enum
+ [ ] Oneof
+ [ ] ...

**Comment by XiaoK29** [comment]
> Contributor

实现的一个小demo：https://github.com/XiaoK29/proto2schema，有什么好的建议或者需要添加的功能

**Comment by XiaoK29** [comment]
> ## Enhancement
> We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.
> 
> ## Reference
> * Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> * Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go



> ## 强化
> 我们想要为 kcl 导入工具添加 protobuf 消息导入，例如 jsonschema、openapi 和 terraform 提供程序架构。
> 
> ## 参考
> * 将 JsonSchema 导入 KCL Schema：https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> * 将 Terraform 提供程序架构导入 KCL 架构：https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go

实现的一个小demo：https://github.com/XiaoK29/proto2schema
如果没啥问题的话，我将把他写入到kcl-go的repo并提交pr

**Comment by XiaoK29** [comment]
> ## Enhancement
> We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.
> 
> ## Reference
> * Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> * Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go

实现的一个小demo：https://github.com/XiaoK29/proto2schema
有什么建议或修改，如果没啥问题的话，我将写入到kcl-go的repo并提交pr

**Comment by Peefy** [comment]
> > ## Enhancement
> > We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.
> > ## Reference
> > 
> > * Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> > * Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go
> 
> 实现的一个小demo：https://github.com/XiaoK29/proto2schema 有什么建议或修改，如果没啥问题的话，我将写入到kcl-go的repo并提交pr

I think there is no problem with implementing the logic. It would be great if we could integrate the existing kcl go code/interfaces and templates. 👍

**Comment by XiaoK29** [comment]
> > > ## Enhancement
> > > We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.
> > > ## Reference
> > > 
> > > * Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> > > * Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go
> > 
> > 
> > 实现的一个小demo：https://github.com/XiaoK29/proto2schema 有什么建议或修改，如果没啥问题的话，我将写入到kcl-go的repo并提交pr
> 
> I think there is no problem with implementing the logic. It would be great if we could integrate the existing kcl go code/interfaces and templates. 👍

好的

**Comment by XiaoK29** [comment]
> > > ## Enhancement
> > > We want to add protobuf message import for the kcl import tool like jsonschema, openapi and terraform provider schema.
> > > ## Reference
> > > 
> > > * Import JsonSchema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_jsonschema.go
> > > * Import Terraform Provider Schema to KCL Schema: https://github.com/kcl-lang/kcl-go/blob/main/pkg/tools/gen/genkcl_terraform.go
> > 
> > 
> > 实现的一个小demo：https://github.com/XiaoK29/proto2schema 有什么建议或修改，如果没啥问题的话，我将写入到kcl-go的repo并提交pr
> 
> I think there is no problem with implementing the logic. It would be great if we could integrate the existing kcl go code/interfaces and templates. 👍

解析是通过pkg/tools/gen/genkcl.go中的GenKclOptions struct来配置的，有个ParseFromTag的字段，proto没有tag这个概念，这个使用proto中的json_name的tag吗？

**Comment by Peefy** [comment]
You can ignore this option.
